### ISSUE TITLE
не ворк

### ISSUE THREAD

**Issue by valerka1292** [mercury-devel/tg_converter#1]
C:\Users\003\Desktop\tdata_soft>main.py
Traceback (most recent call last):
  File "C:\Users\003\Desktop\tdata_soft\main.py", line 1, in <module>
    ﻿from TGConvertor import SessionManager
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\003\AppData\Local\Programs\Python\Python39\lib\site-packages\tgconvertor-0.0.8-py3.9.egg\TGConvertor\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\003\AppData\Local\Programs\Python\Python39\lib\site-packages\tgconvertor-0.0.8-py3.9.egg\TGConvertor\manager.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\003\AppData\Local\Programs\Python\Python39\lib\site-packages\tgconvertor-0.0.8-py3.9.egg\TGConvertor\sessions\pyro.py", line 53, in <module>
  File "C:\Users\003\AppData\Local\Programs\Python\Python39\lib\site-packages\tgconvertor-0.0.8-py3.9.egg\TGConvertor\sessions\pyro.py", line 70, in PyroSession
TypeError: unsupported operand type(s) for |: 'NoneType' and 'type'

**Comment by mercury-devel** [comment]
Поставь отсюда конвертер https://github.com/mercury-devel/tgconvert. Тот что есть в гитхабе обычный, он не работает нормально
